### ISSUE TITLE
Testing Gateways need docs

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#9]
@mathetos commented on [Mon Jan 18 2016](https://github.com/WordImpress/Give-Website/issues/58)

The following documentation articles don't have instructions for testing donations with that specific gateway:
- [x] Authorize.net (https://github.com/WordImpress/Give-Docs/issues/75 assigned to @esolar07 )
- [x] WePay (https://github.com/WordImpress/Give-Docs/issues/76 assigned to @Benunc )
- [x] 2Checkout (https://github.com/WordImpress/Give-Docs/issues/77 assigned to @mathetos)
- [x] PayPal Pro (https://github.com/WordImpress/Give-Docs/issues/78 assigned to @esolar07 )

**Comment by Benunc** [comment]
This is done.
